### ISSUE TITLE
How to Access Sample Dataset Mentioned in 'brainlm_tutorial.ipynb'

### ISSUE THREAD

**Issue by ninicassiel** [vandijklab/BrainLM#8]
Hi! This is Cassiel.
Thanks for your excellent work! According to the brainlm_tutorial.ipynb, there is a reference to a dataset located at /home/mt2286/project/BrainLM/toolkit/sample_dataset/raw_fMRI_data. Could you please provide guidance on how to obtain a similar dataset for experimentation?

**Comment by mihirneal** [comment]
we are unable to share UK Biobank data, however you may use the openly available HCP.
